import { Aleo } from "next/font/google";
import Header from "./src/components/header/header";
import "./globals.css";  // Import global CSS directly, no need to assign it to a variable

const aleo = Aleo({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="description" content={metadata.description} />
        <title>{metadata.title}</title>
      </head>
      <body className={aleo.className}>
        <div className="wrapper">  {/* Use "wrapper" as a string for className */}
          <Header />
          <main>{children}</main>
          <footer>
            {/* Replace with actual footer content */}
          </footer>
        </div>
      </body>
    </html>
  );
}
