import { Aleo } from "next/font/google";
import Header from "./src/components/header/header";
import "./globals.css";

const aleo = Aleo({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="description" content={metadata.description} />
        <title>{metadata.title}</title>
      </head>
      <body className={aleo.className}>
        <Header />
        <main>{children}</main>
        <footer>
          {/* Replace with actual footer content */}
        </footer>
      </body>
    </html>
  );
}
